language: java
deploy:
  provider: heroku
  api_key:
    secure: iR2Gej+Sxuh73oBgVgeTrt2S9jsu4+O3x9w4elP1wLPMYAVIcI7mjW4az5dRDwz/RzHjXrh/YavaGlBvKd7dbfskf9J/Nr7xRR6VI1madBGLD1vLzDW8J2TcVG97JOfS7Qvqe01R3/0REVN3M5C1KNSeik1TBGXB77hPGT/z69Oolx7NZRLUMuRFUdDdTmvuOAcyvrPknP+HxBMQcqUhbrY+LLoFqWcAqaIb31Jnw8/wG5dxYkstDOWoi1FsckYrkXf0rHKKwjpgrinjHja/6GDXclwSpJvlMdn09DhWz8jRY2d0HKc9EalazNwbMiA1OIyas4spQphx/FuwVdik22/TSXCdOCPP21VDKZC4vWinHslSI9Wr7icGsR0jWwnkjRLDhH4VwD3byGeQKsFdmpYr6idAjQL04QJKJesVY6anFlfso+vb2gu2lGRyC7b2RcGTaszVaTZqMGCZj0cwRxwUdxdPPs3aQaIOLIYQAmBzGU16+JbyxAxmmQXS9RwIeH+nukksSJTTjGZjz3u/Hi8g2c5Ej7i5oxeVc75lrdMIIoeZ8tXOCJdMA/nZ2UALBDYvISrNU6Hw1mbhSdvORGDYdlBVP3i+fD6csgyIuWMoFvXh/mhhQgIJiw/thCMftJH5+jr1kZtojPbiciYENmvR+UNOQhsbbAIyEEFFbbM=
  app: sea-battle-back
  on:
    repo: java-park-mail-ru/SeaBattle-09-2017
    branch: develop
  skip_cleanup: true
