language: java
deploy:
  provider: heroku
  api_key:
    secure: ZcVdukJEUo5WxPa1AlX5ZhWJjgdrDwwTdT42IxHvps7Q0aWf+Febw1QcSFuYlvdkAHstPG89aiI9D3hOpmtzvIN5chMDdnRGpX0r6IlnS8Boh/NpdOrX1NbEjEYP8h8KBGW5iMrSBuYcnCqb849Pv/9TQYGYGwMfOEPhlTiRQ4SIXu8CuQRXNP1rPt7NgR2Qdbnga//ajKUMyQ3i7OnOMBaxlIaGEzoR7f5cT9waZMuFd3pkQRW5vpY0RZR8QCL4xFKHVGVTryLk74jDfPi8tESWSrjpCH2W3EIk5hItFHILObXPK+Ec2yxkcaYcrB5leVUho//v+CV3ROXdvYpbwY7q0ZJK64/uFwXnMS5gCi6WCr0I+q4eFYMoW/AhlafL9JqQTKiORH/U/9rsWsdXYgpXo2HY14AYnmONXuFxUNZvsf9GsSyhw3fLu7F63JiGG6QJdX8Pw1//josa/QIpbDF3nvigPvYulddJiuDDK4tV9qarnP8QC6M9LZk9wudpHSIkzRPK529QRUnFexwfB0JD9FCYPwr0tRz3bWcNd/WfL6FCBkeDyZorbbo0p89/Gkwj2+XFBC/jG4lg5j5M8S0XEDctwrIeH7o68kFO4xXtB1FBoYUyOlj0FsDnjIGqpMJZwed8R2SUVzClLHJ4hL9rlw5mljDnL2T3ak4Nh0o=
  app: sea-battle-back
  on:
    repo: java-park-mail-ru/SeaBattle-09-2017
    branch: develop
  skip_cleanup: true
