language: java
deploy:
  provider: heroku
  api_key:
    secure: jYzJ/BLuRCgEUYwhDqCyx4gNFmbNdzshhqJMt4oCs0hYxM//zLtgwOviilow9hyTy2pUjau2VwhSk4YV+v75MLv/uQOBA1nbF9R8JgrC+zniXFCKfqOXuiPb4FGtHxWhbFxkveD8hdzgnjtRTXlDD+z6v36KG7wrFXHaWC85y93Q39wbhU4EjrGbhiErSkO1KU7RQ174tmDtbNYtUPUIO1c2G/9gJmg9FEK/kDhGKByp0z0SoI4nl3osgd7plpfNxpMkD6Fq5B7uzZhEjrRH3bbIhiQ3aKWwkSX9WmMco1DLKwIoKsZ2UwY3FqL07E6FSW2pnHjnPeL+olxvcI0jXzgijbmUoRKuSq0RyNlFThDxJ9J+8jzFqvOTMnC6Aq9QeAKFM+up7lQtdap9TZK4AJE7mBOdFqMnMYIybBKkEY6V8DO6vk7Dqdddq6gwvwr1wXneVleNWEHsK67W4YbECd3J/U1eW/WZ3YPMfnNjDbqAzOpBj+DjoH+C8be5DqkHTOHzGE43v3tFFN8frF+Lai6njCA0XuZnrE4opKyUwrx8RXjicihTzoty0mbiKpabxKlzy6uSOKSiDGUptkKgL+15EramN/1f+D1GhT9q0k2UQ8zNuvRL6LOWIWGsOMfFw9yVMTXu3s3pj7kDqSwZg9ry6foHEzgTII2l2DPhqHA=
  app: sea-battle-back
  on:
    repo: java-park-mail-ru/SeaBattle-09-2017
    branch: develop
  skip_cleanup: true
