language: java
deploy:
  provider: heroku
  api_key:
    secure: "lYAwEu4PJR5uKZC6RH9wcGNW/J3mKu+PLuD4Rxup0srv02kt+zHlXLCATtFgSEXf5P9e+FtybQI54ew4MzMy1Z8ZWAO6CgYJQ4GZq/+TQSTEGA0XxGe0wgYTJ386DQtRp6zuqlqLYMZPL3b7HNx9OJA1nfwKp5eaTS0aALFw3UKNwi1nUd+iAMr4Qu67vhcxJln0+HieDlu7tRn8ak6d4256HbdKNbDeTnf6ER6yg8T2iATI1vpPZeg+oAwJe2IkU81y9QM5kfYtfofHGhGg8NfZv+WW7nY9XLqztXi7Qq+RfL3cwRpjhJgGTUaIFdYcbI/2oqKFzXO7LPQ8IEkuD6n9mA7R0iELYzZPaNt7tK9JYADvQY1vbVPPQ/bnTVJ5+sHgP0ItdOGNlS85Pm89YKFVt2UPtfpz5FlYRB9OFKt5/7xPMYnQg242o0dNwlzh/3KZyjJ2mCBwcWebvQk7B9qNupx9lSMo+TbkAmWhi87BUPbrCqx3aL1m7mHpsMsGNkjXXa36nByHefHyKOY4ruVmh7PqVoUOMy9Rrub9hNDbu6tX1sLquOubuPtbNFxznI9lpAyQmnP1tPxd4VKJRczT2GvZxAufAJMFGNPihz9hydXGvHgUGaanMRt7IKGSyY9th8j5eAZvpwzTgZkQO6eOeNGiVg9pxPqIVQi7Tng="
  app: sea-battle-back
  on:
    repo: java-park-mail-ru/SeaBattle-09-2017
    branch: develop
  skip_cleanup: true
