language: java
deploy:
  provider: heroku
  api_key:
    secure: lz5RwKa+onh7jl/vT8FcWfiw0gP4NzNgCHiVWRrciy/giJ7UHvWj8RfsXcjK6TWjcx0xJhrZlzFp9OD7ROEXdeP8jXCOzV7e5cXYA0FzC41/fIewLdy5C4Z3dPeBGMDcI9BMmXGsuJanP8KkbdYBi34rt0NCFvtR2b34o9NJ2stDH0U2pPgZuWLxO0BVQS1P/DBJx5Snet19BShOx783USZyL7SFS/lxyvB1EPWAjG6N2/cL/rR2C29Hknv1cn4HsW5zfDxdqA8muogcH8P1vI/A2psmilguCNUyRJbXQvHEhqc9afDUgIqCoQACH49JUveplhQcyiRKhdz1HhirCLO2sG//388H2e/xCpkXQKGuqOh9npx7CBbN2HYfYbkZ4+pMyPd4fT7FufvpEEgv2Ra0/rCQeOJnux2DExmCqTtuasPrwgDXZ6N1/KDOd4YMNpJtJRHe3bTrYjvZAWBoMj8Ros9WRizeV8Hk2t4kjTCS7JZhj+2ULjFESjxALM+HACQhS11LJFdqhN+utLD56W7iduYCsddjyZtcA63CLmhyjSVns12Ol8VGiae4BbOs4FNoQhaecK68wV8q0k6Jpk0zPUExhuPgh7c6Xj6ZFLxMzlv5Nz/Gkk0IZW0PKNrRJyBAuqh2/OjCYxV3a0VScXvr/EzjXD7XZ3K4LpoafLs=
  app: sea-battle-back
  on:
    repo: java-park-mail-ru/SeaBattle-09-2017
    branch: develop
  skip_cleanup: true
